### ISSUE TITLE
Complete Random Password generator

### ISSUE THREAD

**Issue by SumitMangrati** [Janani-Balasooriya/Java-Beginner-Projects#10]
I can complete the random password generator since I already have the code for this in my system. I can just pull up a PR and get it done

**Comment by Janani-Balasooriya** [comment]
Hi @SumitMangrati, Thank you for your interest. Someone has already made a pull request for random password generator and we need to wait and see if they will do the requested changes. I will let you know.

**Comment by Janani-Balasooriya** [comment]
Contribution for this issue is also open.
Thank you!!

**Comment by KSVeerendernath** [comment]
Hi @Janani-Balasooriya, Hope you are doing great!! I would like to contribute this for **Hacktoberfest** could you please help to assign it to me.

**Comment by Janani-Balasooriya** [comment]
Hi @KSVeerendernath, Thank you so much for your interest in contributing. I'll review your pull request as soon as possible.
