### ISSUE TITLE
Complete Simple Blog command line project

### ISSUE THREAD

**Issue by Janani-Balasooriya** [Janani-Balasooriya/Java-Beginner-Projects#13]
A minimal command-line blog program implemented in Java. Create and view blog posts with ease.

Features
- Create new blog posts with titles and content.
- View all available blog posts.
- Simple and easy-to-use command-line interface.

[Example Usage](https://github.com/Janani-Balasooriya/Java-Beginner-Projects/blob/main/src/main/java/SimpleBlog/README.md)

**Comment by ngm76** [comment]
Hi @Janani-Balasooriya  can I contribute to this project in Java ?

**Comment by Janani-Balasooriya** [comment]
Sure @ngm76 , this project should be implemented in Java.

**Comment by HarshallSonawane** [comment]
Hey @Janani-Balasooriya , Can i contribute in this project

**Comment by Janani-Balasooriya** [comment]
Sure @HarshallSonawane !  Your contribution is much appreciated. Even you can create a simple blog app using java Swing. 
Feel free to ask me if you have any questions.
Thank you!!

**Comment by HarshallSonawane** [comment]
Can you assign me with this issue!?
