### ISSUE TITLE
Proposal to Create WeatherApp

### ISSUE THREAD

**Issue by ShikariSohan** [Janani-Balasooriya/Java-Beginner-Projects#27]
I would like to propose the creation of a new project called WeatherApp, a command-line tool that fetches and displays weather information for specified locations and the user's current location.

The **WeatherApp** will be a simple and user-friendly command-line application built in Java. It will allow users to:

- Retrieve current weather information for a specific location.
- Automatically fetch the current weather based on the user's IP location.

### Key Features:

1. Location Input:

- Allow users to input a location with multiple words (e.g., "New York City").
- Option to get weather data for the user's current location.

2. Weather Data:

- Fetch weather information using public services like wttr.in or similar.

3. Error Handling 

- Implement basic error handling for invalid inputs and network issues.

4. No External Libraries:

- Ensure that the application does not rely on external libraries or JAR files, keeping it lightweight and easy to use.

### Next Steps: 
I would like to discuss this proposal with the community to gather feedback and refine the project scope before starting the development. Once approved, I will outline a plan for implementation and begin coding.

**Comment by Janani-Balasooriya** [comment]
Thanks for the proposal! It sounds great. Go ahead, and I’ll assign you to the task. 🚀

**Comment by ShikariSohan** [comment]
@Janani-Balasooriya  I have created a pull request. Please review it.
