### ISSUE TITLE
Complete Expense Tracker project

### ISSUE THREAD

**Issue by Janani-Balasooriya** [Janani-Balasooriya/Java-Beginner-Projects#5]
Develop a Java command-line expense tracker that helps you manage your finances. Keep track of your expenses, categorize them, and monitor your spending.

## Features

- Record and categorize expenses.
- View and filter expenses by category.
- Calculate total expenses by category.

**Comment by Sandaru-Dev** [comment]
Hi @Janani-Balasooriya, Can I work on this issue?

**Comment by Janani-Balasooriya** [comment]
Sure @Sandaru-Dev , You can work on this issue. 
Thank you!
