### ISSUE TITLE
Complete Currency Converter project

### ISSUE THREAD

**Issue by Janani-Balasooriya** [Janani-Balasooriya/Java-Beginner-Projects#8]
A simple command-line currency converter implemented in Java. Convert an amount from one currency to another using exchange rates.

[Features](https://github.com/Janani-Balasooriya/Java-Beginner-Projects/blob/main/src/main/java/CurrencyConverter/README.md#features)
Convert an amount from one currency to another.
Supports multiple currency pairs (e.g., USD to EUR, USD to INR).
Fixed exchange rates for demonstration (if can fetch exchange rates from an external source/api).

**Comment by SumitMangrati** [comment]
hey can you assign me this task ill get it done

**Comment by Janani-Balasooriya** [comment]
Hey @SumitMangrati! 
Sure, I'll assign you. Go ahead!

**Comment by SumitMangrati** [comment]
@Janani-Balasooriya I have a doubt, API for currencyExchange rate needs monthly billing subscription. What should i do?

**Comment by Janani-Balasooriya** [comment]
@SumitMangrati no need to worry about the API subscription. For this Java command-line program, we can simply use fixed data for currency exchange rates. 

For example:
        double usdToEurRate = 0.85;
        double usdToInrRate = 74.0;
