### ISSUE TITLE
Complete Quiz Application project

### ISSUE THREAD

**Issue by Janani-Balasooriya** [Janani-Balasooriya/Java-Beginner-Projects#9]
A simple command-line quiz application implemented in Java. Create and take quizzes on various topics.

[Features](https://github.com/Janani-Balasooriya/Java-Beginner-Projects/blob/main/src/main/java/QuizApplication/README.md#features)
Create and customize quizzes with questions and answer choices.
Take quizzes and receive a score.
Supports multiple-choice questions.
Provides immediate feedback on correct and incorrect answers.

[Example questions for the quiz app](https://github.com/Janani-Balasooriya/Java-Beginner-Projects/blob/main/src/main/java/QuizApplication/README.md#example-questions-for-the-quiz-app)

**Comment by MeetD99** [comment]
I would like to work on this Issue, Can you assign it to me please?

**Comment by Janani-Balasooriya** [comment]
Sure @MeetD99! Go ahead. I will assign you.

**Comment by MeetD99** [comment]
Hey @Janani-Balasooriya , I have succesfully added a PR for this Issue. Kindly review it and lemme know of any Changes Required. Thank you! and Happy Coding!

**Comment by Janani-Balasooriya** [comment]
Hi @MeetD99 , You have done a great job! Thank you.

I have requested a small modification. Could you please check it?

Thank you! Happy Coding!
